[package]
name = "vanity_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus   = "1.13.1"
sp-core    = "36.1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
overflow-checks = false
panic = "abort"
incremental = false